name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Compile
        run: yarn compile

      - name: Test
        run: yarn test
