name: Slither-Analyzer
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14


      - name: Use python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9


      - name: Install Dependecies
        run: |
            python -m pip install --upgrade pip
            pip3 install slither-analyzer solc-select
            solc-select install 0.8.1
            solc-select use 0.8.1
            npm ci --ignore-scripts

      - name: Runs Slither
        run: |
            slither . > slither-audit.txt 2>&1
            for SEVERITY in low medium high
                do
                grep ${SEVERITY}' issues' slither-audit.txt | grep -o -E '[0-9]+'
                grep ${SEVERITY}' issues' slither-audit.txt | grep -o -E '[0-9]+' | bc | read ${SEVERITY}_count
              done
            
            echo ${low_count} ${high_count} ${medium_count}
            echo $((low_count+medium_count+high_count))
            if [[ $((low_count+medium_count+high_count)) == 0 ]]
            then
              echo 'Slither has reported no issues'
              exit 0
            else
              echo 'Slither has reported issues'
              exit 1
            fi

